 export const tasks: any = [
   {
     id: "1",
     name: "Новобранец",
     countTask: "от 10 lvl",
     price: "$50",
     order: 1,
   },
   {
     id: "2",
     name: "Рядовой",
     countTask: "10 заданий",
     price: "$80",
     order: 2,
   },
   {
     id: "3",
     name: "Сержант",
     countTask: "5 заданий",
     price: "$100",
     order: 3,
   },
   {
     id: "4",
     name: "Новобранец",
     countTask: "от 10 lvl",
     price: "$50",
     order: 4,
   },
   {
     id: "5",
     name: "Рядовой",
     countTask: "10 заданий",
     price: "$80",
     order: 5,
   },
   {
     id: "6",
     name: "Сержант",
     countTask: "5 заданий",
     price: "$100",
     order: 6,
   },
   {
     id: "7",
     name: "Сержант",
     countTask: "5 заданий",
     price: "$100",
     order: 7,
   },
 ];
